name: SciChap CI
on:
  push:
  release:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chapel-version: [
          '2.8.0',
        ]
    container:
      image: chapel/chapel:${{ matrix.chapel-version }}
    steps:
      - name: Checkout SciChap
        id: checkout
        uses: actions/checkout@v7
      - name: Using Chapel ${{ matrix.chapel-version }}, building package...
        id: build
        run: mason build -- --checks --warnings --debug
      - name: Running tests with Mason...
        id: test
        run: mason test --show
      - name: Running chplcheck...
        id: code-check
        run: chplcheck $(find . -type f -iname "*.chpl")
